export PATH=/usr/local/bin:$PATH
export EDITOR='vim'
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
source "$rvm_path/contrib/prompt"
ps1_set --prompt ∴

